import type { SectionContent } from './ContentContext'

export const initialContent: SectionContent[] = [
    {
    id: 'hero',
    name: 'Hero',
    texts: {
      badge: 'Inteligencia de Mercado 2026',
      title1: 'Transforme-se no',
      title2: 'Vendedor Ideal.',
      subtitle1: 'Aprenda como o seu cliente pensa e fuja da guerra de precos com o',
      subtitle2: 'Manual Solar Buy-Side.',
      ctaButton: 'Entenda a Logica',
      titlePrefix: 'Saia da Disputa de Preco e Passe a',
      titleHighlight: 'Vender Decisoes',
      titleSuffix: 'em Sistema Solar',
      subtitle: 'O metodo Buy-Side ensina voce a pensar como o cliente e conduzir decisoes de compra, nao disputas de preco.',
      manualTitle: 'Manual Solar Buy-Side',
      manualSubtitle: 'Construido a partir da observacao real de como compradores decidem, na pratica.',
      bonusBadge: 'Bonus Exclusivo',
      bonusTitle: 'O Codigo do Vendedor Consultivo',
      bonusSubtitle: 'Para quem quer conduzir decisoes, nao concessoes.',
      ctaSubtext: 'Acesso imediato ao Manual Solar Buy-Side.',
      scrollHint: 'Entenda a logica',
    },
    images: {
      heroImage: '/assets/GED9CF_1_cleanup.PNG',
    },
  },
  {
    id: 'context',
    name: 'Contexto',
    texts: {
      badge: 'Vision 2026',
      title: 'Panorama',
      titleHighlight: '2026',
      subtitle: 'Pode parecer exagero, mas em breve cada vez mais compradores de sistema fotovoltaico estarÃ£o informados.',
      card1Title: 'SaberÃ£o analisar',
      card1Desc: 'CompararÃ£o propostas com precisÃ£o tÃ©cnica superior Ã  mÃ©dia do mercado.',
      card2Title: 'AnalisarÃ£o fundo',
      card2Desc: 'Fornecedores e tecnologias passarÃ£o por um crivo muito mais rigoroso.',
      card3Title: 'AvaliarÃ£o risco',
      card3Desc: 'A confiabilidade da sua empresa serÃ¡ o fator decisivo antes de qualquer preÃ§o.',
      alertTitle: 'Quem nÃ£o entender essa nova jornada vai perder vendas.',
      alertSubtitle: 'O cenÃ¡rio estÃ¡ evoluindo. VocÃª estÃ¡ pronto?',
      solutionBadge: 'A SoluÃ§Ã£o Definitiva',
      solutionTitle: 'Ainda hÃ¡ tempo para reverter essa situaÃ§Ã£o.',
      solutionDesc: 'O Manual de Compra Solar Buy-Side mapeia os novos gatilhos de decisÃ£o do cliente moderno, garantindo que vocÃª esteja do lado certo da venda.',
      check1: 'VisÃ£o do Cliente',
      check2: 'Gatilhos de Compra',
      check3: 'Confiabilidade',
      ctaButton: 'Garantir meu acesso agora',
      ctaSubtext: 'Download Imediato â€¢ PDF Interativo',
    },
    images: {},
  },
  {
    id: 'video',
    name: 'VÃ­deo',
    texts: {
      title: 'Descubra o que o Manual ensina aos compradores e entenda as novas regras do jogo.',
      card1Id: '01',
      card1Tag: 'ProteÃ§Ã£o',
      card1Title: 'Os 3 grandes RISCOS',
      card1Desc: 'Risco integrador (engenharia e suporte), tÃ©cnico (equipamentos e garantias) e financeiro (payback e custo proprietÃ¡rio).',
      card2Id: '02',
      card2Tag: 'AnÃ¡lise',
      card2Title: 'Comprador Informado',
      card2Desc: 'Como identificar promessas exageradas e indÃ­cio de risco em propostas comerciais.',
      card3Id: '03',
      card3Tag: 'EstratÃ©gia',
      card3Title: 'Jornada Planejada',
      card3Desc: 'As 4 fases da decisÃ£o de compra e os momentos exatos nos quais o vendedor perde a venda.',
      alertBadge: 'AtenÃ§Ã£o CrÃ­tica',
      alertTitle: 'Veja o porquÃª de muitos vendedores ficarem fora do jogo.',
      alertSubtitle: 'NÃ£o permita que isso aconteÃ§a com vocÃª.',
      videoBadge: 'ConteÃºdo Exclusivo',
      videoTitle: 'A Nova Realidade Solar',
      videoDuration: '03:54',
    },
    images: {},
  },
  {
    id: 'audience',
    name: 'AudiÃªncia',
    texts: {
      title: 'Quem REALMENTE precisa desse conhecimento?',
      subtitle: 'Veja para quem o Manual Solar Buy-Side Ã© essencial:',
      profile1Title: 'Empresas de IntegraÃ§Ã£o Solar',
      profile1Desc: 'Para vender valor, fugir da guerra dos preÃ§os e fechar mais projetos.',
      profile1Tag: 'ESTRUTURADOS',
      profile1Bullet1: 'Vender valor',
      profile1Bullet2: 'Fechar mais projetos',
      profile2Title: 'Empreendedores Iniciantes',
      profile2Desc: 'Para construir um negÃ³cio sÃ³lido desde o primeiro passo na integraÃ§Ã£o solar.',
      profile2Tag: 'STARTUPS',
      profile2Bullet1: 'Base sÃ³lida',
      profile2Bullet2: 'Autoridade desde o dia 1',
      profile3Title: 'Representantes Comerciais',
      profile3Desc: 'Para aumentar sua taxa de conversÃ£o reduzindo sua taxa de desconto.',
      profile3Tag: 'VENDAS',
      profile3Bullet1: 'Menos desconto',
      profile3Bullet2: 'Mais conversÃ£o',
      bottomTitle: 'NÃ£o importa em qual ponto da cadeia vocÃª estÃ¡, o Manual Solar Buy-Side nÃ£o Ã© apenas um guia, mas uma imersÃ£o completa na perspectiva do comprador.',
    },
    images: {},
  },
  {
    id: 'manual-strategic',
    name: 'Manual EstratÃ©gico',
    texts: {
      badge: 'A ferramenta estratÃ©gica',
      title: 'Manual Solar Buy-Side',
      subtitle: 'A ferramenta estratÃ©gica que todo vendedor do setor solar precisa ter.',
      description1: 'O Manual de Compra Solar Buy-Side Ã© uma leitura essencial para profissionais do setor de vendas (Sell-Side) que desejam se destacar em um mercado ultracompetitivo.',
      description2: 'Ao proporcionar uma imersÃ£o na jornada de compra sob a Ã³tica do comprador, este manual oferece uma compreensÃ£o estratÃ©gica dos critÃ©rios, motivaÃ§Ãµes e desafios enfrentados pelo lado comprador (Buy-Side).',
      description3: 'Ao dominar o conceito Buy-Side, vendedores estarÃ£o aptos a lapidar sua abordagem comercial, entregar valor real, distanciar-se da briga por preÃ§o e elevar sua credibilidade no relacionamento com os clientes.',
      ctaButton: 'QUERO VENDER COM ESTRATÃ‰GIA AVANÃ‡ADA',
      section2Title: '',
      section2Subtitle: '',
      sellSideHeader: 'O que o vendedor vai dominar',
      sellCard1Title: 'Dores reais do cliente',
      sellCard1Desc: 'Compreende o que realmente pesa na decisÃ£o, nÃ£o apenas o que ele diz na reuniÃ£o.',
      sellCard2Title: 'Postura consultiva',
      sellCard2Desc: 'NÃ£o dispute por preÃ§o, dispute por valor. Ajude o cliente a decidir com seguranÃ§a e fortaleÃ§a uma relaÃ§Ã£o de longo prazo.',
      sellCard3Title: 'Valor tÃ©cnico e econÃ´mico',
      sellCard3Desc: 'Demonstra, de forma fundamentada, como o valor tÃ©cnico da soluÃ§Ã£o se converte em benefÃ­cio econÃ´mico.',
      focusHeader: 'Principais focos e habilidades',
      focusCard1Title: 'ApresentaÃ§Ãµes persuasivas',
      focusCard1Desc: 'Estruture propostas objetivas e transparentes que facilitam a decisÃ£o do cliente.',
      focusCard2Title: 'Domine a Venda',
      focusCard2Desc: 'Conquiste autoridade e crie conexÃµes reais para fechar mais negÃ³cios.',
      focusCard3Title: 'Menos desconto, mais margem',
      focusCard3Desc: 'Argumente com precisÃ£o e preserve sua comissÃ£o sem perder vendas.',
    },
    images: {
      manual: '/assets/manual.jpg.png',
    },
  },
  {
    id: 'testimonials',
    name: 'Depoimentos',
    texts: {
      quote: '"Em um mÃªs fechei 5 sistemas novos"',
      subtitle: 'Os benefÃ­cios sÃ£o claros, e a prÃ¡tica comprova.',
      label: 'Veja a experiÃªncia de Rodrigo, Integrador de SÃ£o Paulo',
      text1: '"Eu sofria com a concorrÃªncia acirrada e a baixa conversÃ£o. O Manual Solar Buy-Side me mostrou como entender a perspectiva do cliente, e isso mudou o jogo."',
      text2: '"Em um mÃªs, fechei 5 sistemas novos. O mais gratificante, porÃ©m, foi a conexÃ£o. Deixei de ser apenas um vendedor e me tornei um verdadeiro parceiro para meus clientes."',
      calloutTitle: 'FaÃ§a como ele',
      calloutText: 'ImersÃ£o no Manual de Compra Solar Buy-Side: pense como seu cliente e torne-se um Vendedor de Alta Performance!',
      name: 'Rodrigo',
      role: 'Integrador Solar, SP',
      metric: '+5 Sistemas',
      metricLabel: 'Fechados em 30 dias',
    },
    images: {
      avatar: '/assets/Integrador_Rodrigo_SP.png',
    },
  },
  {
    id: 'story-bridge',
    name: 'Ponte HistÃ³ria',
    texts: {
      title: 'A histÃ³ria de Rodrigo Ã© apenas um exemplo do poder deste manual.',
      subtitle: 'Ele Ã© uma ponte entre o comprador bem informado e o vendedor preparado, impulsionando negociaÃ§Ãµes justas e satisfatÃ³rias.',
      feature1Title: 'ConteÃºdo TÃ©cnico',
      feature1Desc: 'Mais de 130 pÃ¡ginas com conteÃºdo tÃ©cnico e estratÃ©gico.',
      feature2Title: 'Consulta RÃ¡pida',
      feature2Desc: '160 tÃ³picos organizados para consulta rÃ¡pida.',
      feature3Title: 'Jornada de Compra',
      feature3Desc: 'Uma metodologia em 4 fases que orienta toda a jornada de compra.',
      feature4Title: 'Suporte DecisÃ³rio',
      feature4Desc: 'Anexos tÃ©cnicos que auxiliam na tomada de decisÃ£o.',
    },
    images: {
      manual: '/assets/manualdecompra1.png',
    },
  },
  {
    id: 'seller-code',
    name: 'CÃ³digo do Vendedor',
    texts: {
      title: 'O Segredo por trÃ¡s dos resultados: O CÃ³digo do Vendedor Consultivo',
      subtitle: 'O sucesso do Rodrigo nÃ£o foi por acaso. AlÃ©m de aplicar o Manual Solar Buy-Side, ele dominou a estratÃ©gia que inverte o jogo: aprender a pensar como um comprador para dominar a venda.',
      bonusBadge: 'Oferta Especial',
      bonusTitle: '[BÃ”NUS EXCLUSIVO]',
      ebookTitle: 'E-book: O CÃ³digo do Vendedor Consultivo',
      ebookSubtitle: 'O mÃ©todo de imersÃ£o no Manual Solar Buy-Side para quem nÃ£o aceita mais perder vendas por preÃ§o.',
      listHeader: 'O que vocÃª vai dominar:',
      item1Title: 'Ãndice de Confiabilidade',
      item1Desc: 'Aprenda a medir e provar a seguranÃ§a da sua proposta de forma estruturada e profissional.',
      item2Title: 'Ajuste de PrecisÃ£o com Checklist',
      item2Desc: 'Refine seus materiais de vendas com base no que compradores realmente avaliam (e o que eles descartam).',
      item3Title: 'EstratÃ©gia Anti-LeilÃ£o',
      item3Desc: 'Saiba exatamente como agir com clientes focados apenas em preÃ§o e recupere sua margem de lucro.',
      item4Title: 'Postura Consultiva de Elite',
      item4Desc: 'Prepare-se para fechar contratos com clientes tÃ©cnicos e criteriosos que costumam ignorar vendedores comuns.',
    },
    images: {
      book: '/assets/o-codigo-oficial-4.png',
    },
  },
  {
    id: 'pricing',
    name: 'Oferta',
    texts: {
      badge: 'PrÃ©-venda profissional por tempo limitado',
      title: '',
      titleHighlight: '',
      subtitle: '',
      sectionTitle: 'VEJA TUDO QUE VOCÃŠ RECEBE:',
      feature1Tag: 'VITALÃCIO',
      feature1Title: 'Manual Solar Buy-Side',
      feature1Desc: 'Acesso imediato Ã  bÃ­blia da estratÃ©gia solar.',
      feature2Tag: 'TÃ‰CNICO',
      feature2Title: '130 PÃ¡ginas + 160 TÃ³picos',
      feature2Desc: 'ConteÃºdo denso e interativo. Sem enrolaÃ§Ã£o.',
      feature3Tag: 'ESTRATÃ‰GIA',
      feature3Title: 'MÃ©todo em 4 Fases',
      feature3Desc: 'A jornada de compra completa decifrada.',
      feature4Tag: 'EXCLUSIVO',
      feature4Title: 'Anexos TÃ©cnicos',
      feature4Desc: 'DocumentaÃ§Ã£o exclusiva para pronta aplicaÃ§Ã£o.',
      bonusBadge: 'BÃ”NUS EXCLUSIVO',
      bonusTitle: 'CÃ³digo de Vendedor Consultivo',
      bonusSubtitle: 'VocÃª vendendo decisÃ£o, nÃ£o preÃ§o',
      planBadge: 'Plano de Acesso',
      planTitle: 'Oferta Especial',
      priceOriginal: 'De R$ 997,00 por apenas:',
      priceInstallments: '12x de R$ 61,38',
      priceCash: 'Ou R$ 597,00 Ã  vista no PIX',
      ctaButton: 'ACESSAR O MANUAL AGORA',
      benefit1: 'LiberaÃ§Ã£o imediata no seu e-mail',
      benefit2: 'Checkout 100% criptografado',
      benefit3: 'Acesso Imediato',
      timerLabel: 'Sua oferta expira em:',
    },
    images: {
      guarantee: '/assets/Garantia.png',
      visa: '/assets/Visa.png',
      mastercard: '/assets/Mastercard.png',
      pix: '/assets/Pix.png',
      boleto: '/assets/Boleto.png',
      securePurchase: '/assets/Compra segura.png',
    },
  },
  {
    id: 'buyer-wave',
    name: 'Onda do Comprador',
    texts: {
      badge: 'MANUAL DO COMPRADOR',
      title: '',
      subtitle: 'Compradores estÃ£o evoluindo. Veja o que eles estarÃ£o aprendendo em breve.',
      card1Title: 'O que o comprador vai dominar?',
      card1Item1: 'Conceitos essenciais para uma compra tÃ©cnica e segura',
      card1Item2: 'Reconhecimento de marcas e distribuidores de alta confianÃ§a',
      card1Item3: 'CritÃ©rios para selecionar empresas de integraÃ§Ã£o solar sÃ©rias e competentes',
      card2Title: 'Principais focos e Habilidades',
      card2Item1: 'Analisar propostas com critÃ©rios tÃ©cnicos e financeiros',
      card2Item2: 'Avaliar reputaÃ§Ã£o e suporte de pÃ³s-venda com precisÃ£o',
      card2Item3: 'Tomar decisÃ£o com seguranÃ§a e embasamento tÃ©cnico',
      testimonialsTitle: 'As vozes de quem aprendeu',
      testimonialsSubtitle: 'Relatos de compradores informados e preparados',
      ctaText1: 'ComeÃ§ar agora',
      ctaText2: 'Acessar Guia EstratÃ©gico',
    },
    images: {},
  },
  {
    id: 'authority',
    name: 'Autoridade',
    texts: {
      badge: 'ExperiÃªncia Dual',
      title: 'Este conteÃºdo foi concebido por quem domina, as duas perspectivas da mesa de negociaÃ§Ã£o â€” a do comprador e a do vendedor.',
      person1Badge: 'Especialista',
      person1Name: 'Francis Poloni',
      person1Desc: 'Atua desde 2018 no setor de integraÃ§Ã£o fotovoltaica e consultoria onde assessorou tanto no lado do comprador (Buy-Side) quanto no lado do vendedor (Sell-Side), ajudando na tomada de decisÃµes inteligentes e seguras.',
      person1Tag: 'Especialista VisÃ£o Buy-Side (Comprador)',
      person1Experience: '+7 Anos',
      person1ExperienceLabel: 'de experiÃªncia',
      person2Badge: 'Especialista',
      person2Name: 'OvÃ­dio Collesi',
      person2Desc: 'Com vasta experiÃªncia em venda e pÃ³s venda no setor de energia solar fotovoltaica desde 2020, teve passagens por marketplaces, distribuidores, integraÃ§Ã£o solar e certificadora, trazendo uma visÃ£o completa do lado do vendedor e do suporte tÃ©cnico.',
      person2Tag: 'Especialista VisÃ£o Sell-Side (Vendedor)',
      person2Experience: '+5 Anos',
      person2ExperienceLabel: 'de experiÃªncia',
    },
    images: {
      francis: '/assets/Francis Poloni LP PRO.jpg.jpeg',
      ovidio: '/assets/OvÃ­dio2.png',
    },
  },
  {
    id: 'lead-magnet',
    name: 'Lead Magnet',
    texts: {
      badge: 'ConteÃºdo Exclusivo',
      title: 'Ainda tem dÃºvidas sobre o impacto do Manual Buy-Side?',
      subtitle: 'Garanta agora seu e-book grÃ¡tis e entenda por que a imersÃ£o Solar Buy-Side faz vendedores venderem mais e melhor.',
      feature1: 'Os 3 riscos na compra de sistemas solares',
      feature2: 'As 4 fases que seu cliente seguirÃ¡ antes de comprar',
      feature3: 'Como sua proposta serÃ¡ avaliada e comparada',
      feature4: 'O Ã­ndice detalhado do Manual Solar Buy-Side',
      ctaButton: 'Baixar E-book Gratuito',
      ctaSubtext: 'PDF Interativo â€¢ 24 pÃ¡ginas â€¢ Acesso imediato',
      modalTitle: 'Baixe seu E-book',
      modalSubtitle: 'Preencha seus dados para receber o E-book Manual Solar Buy-Side',
      successTitle: 'Perfeito!',
      successMessage: 'Confira seu e-mail para baixar o E-book Manual Solar Buy-Side',
    },
    images: {
      ebook: '/assets/Capa do Vendedor E-book  - OF.png',
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    texts: {
      title: 'Fique por dentro das novidades',
      highlightWord: 'novidades',
      subtitle: 'Cadastre seu e-mail para receber lanÃ§amentos exclusivos, atualizaÃ§Ãµes e conteÃºdos sobre o mercado solar.',
      placeholder: 'seu@email.com',
      ctaButton: 'Cadastrar',
      successButton: 'Cadastrado!',
      successMessage: 'E-mail cadastrado com sucesso! Fique atento Ã s novidades.',
      privacyNote: 'ðŸ”’ Seus dados estÃ£o seguros conosco. NÃ£o compartilhamos com terceiros.',
    },
    images: {},
  },
  {
    id: 'faq',
    name: 'FAQ',
    texts: {
      title: 'Ficou com dÃºvidas?',
      subtitle: 'Nossa equipe de especialistas estÃ¡ pronta para ajudar vocÃª a entender como o Manual Buy-Side pode transformar sua operaÃ§Ã£o comercial.',
      ctaButton: 'Fale com a equipe Buy-Side',
      sectionTitle: 'Perguntas Frequentes',
      faq1Question: 'Como acessar meu produto?',
      faq1Answer: 'VocÃª receberÃ¡ o acesso ao Manual Solar Buy-Side por e-mail, por meio da plataforma online GREENN. Esta plataforma atua como intermediadora digital entre clientes e produtores, disponibilizando conteÃºdos, soluÃ§Ãµes e ferramentas tecnolÃ³gicas.\n\nVocÃª receberÃ¡ o Manual Solar Buy-Side e o bÃ´nus grÃ¡tis Guia do Vendedor por e-mail em PDF, e ele virÃ¡ personalizado com seu nome e CPF ou CNPJ.\n\nVocÃª poderÃ¡ acessar o manual por meio de computador, celular, tablet ou outro dispositivo digital. No entanto, devido Ã  formataÃ§Ã£o do manual, recomendamos enfaticamente o uso de um computador ou tablet para uma experiÃªncia de leitura e aproveitamento mais otimizada do material.',
      faq2Question: 'Como funciona o prazo de garantia e a solicitaÃ§Ã£o de devoluÃ§Ã£o?',
      faq2Answer: 'O reembolso de uma compra de um produto digital Ã© um direito garantido pelo CÃ³digo de Defesa do Consumidor (Lei nÂº 8.078, Artigo 49) e pode ser solicitado em atÃ© 7 dias a partir da data de assinatura ou do recebimento do produto.',
      faq3Question: 'PolÃ­tica de devoluÃ§Ã£o: como proceder para o reembolso?',
      faq3Answer: 'Para formalizar o pedido de reembolso do valor despendido, o Comprador deverÃ¡ remeter sua solicitaÃ§Ã£o ao endereÃ§o eletrÃ´nico contato@buyside.com.br. A comunicaÃ§Ã£o deverÃ¡ conter, obrigatoriamente, o nÃºmero de referÃªncia da transaÃ§Ã£o e a exposiÃ§Ã£o detalhada da(s) razÃ£o(Ãµes) que fundamenta(m) o pleito de cancelamento.\n\nAs condiÃ§Ãµes para efetivaÃ§Ã£o do reembolso pautam-se nas Regras Gerais estabelecidas pela plataforma GREENN. Para informaÃ§Ãµes adicionais e consulta integral Ã s diretrizes aplicÃ¡veis, o Comprador poderÃ¡ acessar o seguinte link: https://greenn.com.br/termos-de-compra-greenn/\n\nSolicitaÃ§Ã£o de Cancelamento e Reembolsos na GREENN\n\nPrazo: O Comprador pode solicitar o reembolso dos valores pagos, os prazos mÃ­nimos estabelecidos pela legislaÃ§Ã£o para garantia sÃ£o entre 07 a 30 dias, mas dependem exclusivamente do prazo estabelecido pelo Produtor, que Ã© o responsÃ¡vel direto por esta informaÃ§Ã£o e pelas solicitaÃ§Ãµes e as autorizaÃ§Ãµes dos reembolsos. O prazo terÃ¡ inÃ­cio a partir da efetivaÃ§Ã£o da compra, pedidos de reembolso fora do prazo deverÃ£o ser feitos diretamente ao Produtor, e se por ele autorizados, salvo quando o reembolso deva ser processado para garantir os interesses do GREENN e para o cumprimento da lei.\n\nO GREENN pode recusar o reembolso integral dos valores pagos, ainda que dentro do prazo de garantia, na hipÃ³tese do Comprador ter usufruÃ­do de todo o Produto adquirido, como por exemplo, assistido a todas as aulas de um curso, participado de um evento, ou ter feito o download de todos os arquivos disponÃ­veis, deixando o GREENN e o Produtor em clara desvantagem.\n\nForma de processamento: O reembolso serÃ¡ processado atravÃ©s do mesmo meio de pagamento escolhido pelo Comprador no momento da compra, por questÃµes legais e processuais. O reembolso Ã© realizado por meio de transferÃªncia bancÃ¡ria deve ocorrer em atÃ© 30 (trinta) dias, contados da data de solicitaÃ§Ã£o. Nos casos de reembolso por meio de cartÃ£o de crÃ©dito, o GREENN farÃ¡ a solicitaÃ§Ã£o de estorno, mas a conclusÃ£o deste processo dependerÃ¡ exclusivamente das operadoras de cartÃ£o, sem qualquer gerÃªncia do GREENN e poderÃ¡ levar um prazo de 30 a 60 dias, apÃ³s o pedido de estorno.\n\nSe o reembolso nÃ£o ocorrer dentro dos prazos acima, o Comprador deverÃ¡ entrar em contato com o GREENN. Se o reembolso for por intermÃ©dio de cartÃ£o de crÃ©dito, findado o prazo de 90 (noventa) dias, o Comprador se compromete a enviar as cÃ³pias de suas faturas para que o Greenn possa endereÃ§ar este assunto perante a operadora e finalizar o processo de reembolso. O comprador concorda que o nÃ£o envio das faturas impede o Greenn de dar seguimento ao processo de investigaÃ§Ã£o e conclusÃ£o do processo de estorno do pagamento.\n\nCanal de ReclamaÃ§Ãµes: O Comprador pode solicitar cancelamento de sua compra de maneira independente, atravÃ©s do link www.reclamacao.greenn.com.br , bastando informar corretamente os dados solicitados e seguindo os procedimentos e orientaÃ§Ãµes anteriormente colocados quanto a legalidade e prazos.',
    },
    images: {},
  },
  {
    id: 'contact',
    name: 'Contato',
    texts: {
      title: 'DADOS E CONTATOS',
      subtitle: 'Transparencia e clareza para voce entrar em contato com total confianca.',
      companyName: 'Buy-Side Solucoes',
      cnpjLabel: 'CNPJ:',
      cnpjValue: '55.463.06/0001-80',
      addressLine1: 'Torre Norte - Av. Bento Munhoz da Rocha Neto, 632',
      addressLine2: '19o Andar, Salas 1905 a 1908 - Zona 7,',
      addressLine3: 'Maringa - PR, 87030-010',
      emailLabel: 'E-mail:',
      emailAddress: 'contato@buyside.com.br',
    },
    images: {},
  },
  {
    id: 'privacy-policy',
    name: 'PolÃ­tica de Privacidade',
    texts: {
      content: 'ConteÃºdo da polÃ­tica de privacidade...',
    },
    images: {},
  },
  {
    id: 'terms-of-use',
    name: 'Termos de Uso',
    texts: {
      content: 'ConteÃºdo dos termos de uso...',
    },
    images: {},
  },
  {
    id: 'antipiracy',
    name: 'Medidas Antipiratarias',
    texts: {
      content: 'ConteÃºdo das medidas antipiratarias...',
    },
    images: {},
  },
]


