import type { SectionContent } from './ContentContext'

export const initialContent: SectionContent[] = [
  {
    id: 'hero',
    name: 'Hero',
    texts: {
      badge: 'Inteligência de Mercado 2026',
      title1: 'Transforme-se no',
      title2: 'Vendedor Ideal.',
      subtitle1: 'Aprenda como o seu cliente pensa e fuja da guerra de preços com o',
      subtitle2: 'Manual Solar Buy-Side.',
      ctaButton: 'Entenda a Lógica',
    },
    images: {},
  },
  {
    id: 'context',
    name: 'Contexto',
    texts: {
      badge: 'Vision 2026',
      title: 'Panorama 2026',
      subtitle: 'Pode parecer exagero, mas em breve cada vez mais compradores de sistema fotovoltaico estarão informados.',
      card1Title: 'Saberão analisar',
      card1Desc: 'Compararão propostas com precisão técnica superior à média do mercado.',
      card2Title: 'Analisarão fundo',
      card2Desc: 'Fornecedores e tecnologias passarão por um crivo muito mais rigoroso.',
      card3Title: 'Avaliarão risco',
      card3Desc: 'A confiabilidade da sua empresa será o fator decisivo antes de qualquer preço.',
      alertTitle: 'Quem não entender essa nova jornada vai perder vendas.',
      alertSubtitle: 'O cenário está evoluindo. Você está pronto?',
      solutionBadge: 'A Solução Definitiva',
      solutionTitle: 'Ainda há tempo para reverter essa situação.',
      solutionDesc: 'O Manual de Compra Solar Buy-Side mapeia os novos gatilhos de decisão do cliente moderno, garantindo que você esteja do lado certo da venda.',
      check1: 'Visão do Cliente',
      check2: 'Gatilhos de Compra',
      check3: 'Confiabilidade',
      ctaButton: 'Garantir meu acesso agora',
      ctaSubtext: 'Download Imediato • PDF Interativo',
    },
    images: {},
  },
  {
    id: 'video',
    name: 'Vídeo',
    texts: {
      title: 'Descubra o que o Manual ensina aos compradores e entenda as novas regras do jogo.',
      card1Id: '01',
      card1Tag: 'Proteção',
      card1Title: 'Os 3 grandes RISCOS',
      card1Desc: 'Risco integrador (engenharia e suporte), técnico (equipamentos e garantias) e financeiro (payback e custo proprietário).',
      card2Id: '02',
      card2Tag: 'Análise',
      card2Title: 'Comprador Informado',
      card2Desc: 'Como identificar promessas exageradas e indício de risco em propostas comerciais.',
      card3Id: '03',
      card3Tag: 'Estratégia',
      card3Title: 'Jornada Planejada',
      card3Desc: 'As 4 fases da decisão de compra e os momentos exatos nos quais o vendedor perde a venda.',
      alertBadge: 'Atenção Crítica',
      alertTitle: 'Veja o porquê de muitos vendedores ficarem fora do jogo.',
      alertSubtitle: 'Não permita que isso aconteça com você.',
      videoBadge: 'Conteúdo Exclusivo',
      videoTitle: 'A Nova Realidade Solar',
      videoDuration: '03:54',
    },
    images: {},
  },
  {
    id: 'audience',
    name: 'Audiência',
    texts: {
      title: 'Quem REALMENTE precisa desse conhecimento?',
      subtitle: 'Veja para quem o Manual Solar Buy-Side é essencial:',
      profile1Title: 'Empresas de Integração Solar',
      profile1Desc: 'Para vender valor, fugir da guerra dos preços e fechar mais projetos.',
      profile1Tag: 'ESTRUTURADOS',
      profile1Bullet1: 'Vender valor',
      profile1Bullet2: 'Fechar mais projetos',
      profile2Title: 'Empreendedores Iniciantes',
      profile2Desc: 'Para construir um negócio sólido desde o primeiro passo na integração solar.',
      profile2Tag: 'STARTUPS',
      profile2Bullet1: 'Base sólida',
      profile2Bullet2: 'Autoridade desde o dia 1',
      profile3Title: 'Representantes Comerciais',
      profile3Desc: 'Para aumentar sua taxa de conversão reduzindo sua taxa de desconto.',
      profile3Tag: 'VENDAS',
      profile3Bullet1: 'Menos desconto',
      profile3Bullet2: 'Mais conversão',
      bottomTitle: 'Não importa em qual ponto da cadeia você está, o Manual Solar Buy-Side não é apenas um guia, mas uma imersão completa na perspectiva do comprador.',
    },
    images: {},
  },
  {
    id: 'manual-strategic',
    name: 'Manual Estratégico',
    texts: {
      badge: 'A ferramenta estratégica',
      title: 'Manual Solar Buy-Side',
      subtitle: 'A ferramenta estratégica que todo vendedor do setor solar precisa ter.',
      description1: 'O Manual de Compra Solar Buy-Side é uma leitura essencial para profissionais do setor de vendas (Sell-Side) que desejam se destacar em um mercado ultracompetitivo.',
      description2: 'Ao proporcionar uma imersão na jornada de compra sob a ótica do comprador, este manual oferece uma compreensão estratégica dos critérios, motivações e desafios enfrentados pelo lado comprador (Buy-Side).',
      description3: 'Ao dominar o conceito Buy-Side, vendedores estarão aptos a lapidar sua abordagem comercial, entregar valor real, distanciar-se da briga por preço e elevar sua credibilidade no relacionamento com os clientes.',
      ctaButton: 'QUERO VENDER COM ESTRATÉGIA AVANÇADA',
      section2Title: '',
      section2Subtitle: '',
      sellSideHeader: 'O que o vendedor vai dominar',
      sellCard1Title: 'Dores reais do cliente',
      sellCard1Desc: 'Compreende o que realmente pesa na decisão, não apenas o que ele diz na reunião.',
      sellCard2Title: 'Postura consultiva',
      sellCard2Desc: 'Não dispute por preço, dispute por valor. Ajude o cliente a decidir com segurança e fortaleça uma relação de longo prazo.',
      sellCard3Title: 'Valor técnico e econômico',
      sellCard3Desc: 'Demonstra, de forma fundamentada, como o valor técnico da solução se converte em benefício econômico.',
      focusHeader: 'Principais focos e habilidades',
      focusCard1Title: 'Apresentações persuasivas',
      focusCard1Desc: 'Estruture propostas objetivas e transparentes que facilitam a decisão do cliente.',
      focusCard2Title: 'Domine a Venda',
      focusCard2Desc: 'Conquiste autoridade e crie conexões reais para fechar mais negócios.',
      focusCard3Title: 'Menos desconto, mais margem',
      focusCard3Desc: 'Argumente com precisão e preserve sua comissão sem perder vendas.',
    },
    images: {
      manual: '/assets/manual.jpg.png',
    },
  },
  {
    id: 'testimonials',
    name: 'Depoimentos',
    texts: {
      quote: '"Em um mês fechei 5 sistemas novos"',
      subtitle: 'Os benefícios são claros, e a prática comprova.',
      label: 'Veja a experiência de Rodrigo, Integrador de São Paulo',
      text1: '"Eu sofria com a concorrência acirrada e a baixa conversão. O Manual Solar Buy-Side me mostrou como entender a perspectiva do cliente, e isso mudou o jogo."',
      text2: '"Em um mês, fechei 5 sistemas novos. O mais gratificante, porém, foi a conexão. Deixei de ser apenas um vendedor e me tornei um verdadeiro parceiro para meus clientes."',
      calloutTitle: 'Faça como ele',
      calloutText: 'Imersão no Manual de Compra Solar Buy-Side: pense como seu cliente e torne-se um Vendedor de Alta Performance!',
      name: 'Rodrigo',
      role: 'Integrador Solar, SP',
      metric: '+5 Sistemas',
      metricLabel: 'Fechados em 30 dias',
    },
    images: {
      avatar: '/assets/Integrador_Rodrigo_SP.png',
    },
  },
  {
    id: 'story-bridge',
    name: 'Ponte História',
    texts: {
      title: 'A história de Rodrigo é apenas um exemplo do poder deste manual.',
      subtitle: 'Ele é uma ponte entre o comprador bem informado e o vendedor preparado, impulsionando negociações justas e satisfatórias.',
      feature1Title: 'Conteúdo Técnico',
      feature1Desc: 'Mais de 130 páginas com conteúdo técnico e estratégico.',
      feature2Title: 'Consulta Rápida',
      feature2Desc: '160 tópicos organizados para consulta rápida.',
      feature3Title: 'Jornada de Compra',
      feature3Desc: 'Uma metodologia em 4 fases que orienta toda a jornada de compra.',
      feature4Title: 'Suporte Decisório',
      feature4Desc: 'Anexos técnicos que auxiliam na tomada de decisão.',
    },
    images: {
      manual: '/assets/manualdecompra1.png',
    },
  },
  {
    id: 'seller-code',
    name: 'Código do Vendedor',
    texts: {
      title: 'O Segredo por trás dos resultados: O Código do Vendedor Consultivo',
      subtitle: 'O sucesso do Rodrigo não foi por acaso. Além de aplicar o Manual Solar Buy-Side, ele dominou a estratégia que inverte o jogo: aprender a pensar como um comprador para dominar a venda.',
      bonusBadge: 'Oferta Especial',
      bonusTitle: '[BÔNUS EXCLUSIVO]',
      ebookTitle: 'E-book: O Código do Vendedor Consultivo',
      ebookSubtitle: 'O método de imersão no Manual Solar Buy-Side para quem não aceita mais perder vendas por preço.',
      listHeader: 'O que você vai dominar:',
      item1Title: 'Índice de Confiabilidade',
      item1Desc: 'Aprenda a medir e provar a segurança da sua proposta de forma estruturada e profissional.',
      item2Title: 'Ajuste de Precisão com Checklist',
      item2Desc: 'Refine seus materiais de vendas com base no que compradores realmente avaliam (e o que eles descartam).',
      item3Title: 'Estratégia Anti-Leilão',
      item3Desc: 'Saiba exatamente como agir com clientes focados apenas em preço e recupere sua margem de lucro.',
      item4Title: 'Postura Consultiva de Elite',
      item4Desc: 'Prepare-se para fechar contratos com clientes técnicos e criteriosos que costumam ignorar vendedores comuns.',
    },
    images: {
      book: '/assets/o-codigo-oficial-4.png',
    },
  },
  {
    id: 'pricing',
    name: 'Oferta',
    texts: {
      badge: 'Pré-venda profissional por tempo limitado',
      title: '',
      titleHighlight: '',
      subtitle: '',
      sectionTitle: 'VEJA TUDO QUE VOCÊ RECEBE:',
      feature1Tag: 'VITALÍCIO',
      feature1Title: 'Manual Solar Buy-Side',
      feature1Desc: 'Acesso imediato à bíblia da estratégia solar.',
      feature2Tag: 'TÉCNICO',
      feature2Title: '130 Páginas + 160 Tópicos',
      feature2Desc: 'Conteúdo denso e interativo. Sem enrolação.',
      feature3Tag: 'ESTRATÉGIA',
      feature3Title: 'Método em 4 Fases',
      feature3Desc: 'A jornada de compra completa decifrada.',
      feature4Tag: 'EXCLUSIVO',
      feature4Title: 'Anexos Técnicos',
      feature4Desc: 'Documentação exclusiva para pronta aplicação.',
      bonusBadge: 'BÔNUS EXCLUSIVO',
      bonusTitle: 'Código de Vendedor Consultivo',
      bonusSubtitle: 'Você vendendo decisão, não preço',
      planBadge: 'Plano de Acesso',
      planTitle: 'Oferta Especial',
      priceOriginal: 'De R$ 997,00 por apenas:',
      priceInstallments: '12x de R$ 61,38',
      priceCash: 'Ou R$ 597,00 à vista no PIX',
      ctaButton: 'ACESSAR O MANUAL AGORA',
      benefit1: 'Liberação imediata no seu e-mail',
      benefit2: 'Checkout 100% criptografado',
      benefit3: 'Acesso Imediato',
      timerLabel: 'Sua oferta expira em:',
    },
    images: {
      guarantee: '/assets/Garantia.png',
      visa: '/assets/Visa.png',
      mastercard: '/assets/Mastercard.png',
      pix: '/assets/Pix.png',
      boleto: '/assets/Boleto.png',
      securePurchase: '/assets/Compra segura.png',
    },
  },
  {
    id: 'buyer-wave',
    name: 'Onda do Comprador',
    texts: {
      badge: 'MANUAL DO COMPRADOR',
      title: '',
      subtitle: 'Compradores estão evoluindo. Veja o que eles estarão aprendendo em breve.',
      card1Title: 'O que o comprador vai dominar?',
      card1Item1: 'Conceitos essenciais para uma compra técnica e segura',
      card1Item2: 'Reconhecimento de marcas e distribuidores de alta confiança',
      card1Item3: 'Critérios para selecionar empresas de integração solar sérias e competentes',
      card2Title: 'Principais focos e Habilidades',
      card2Item1: 'Analisar propostas com critérios técnicos e financeiros',
      card2Item2: 'Avaliar reputação e suporte de pós-venda com precisão',
      card2Item3: 'Tomar decisão com segurança e embasamento técnico',
      testimonialsTitle: 'As vozes de quem aprendeu',
      testimonialsSubtitle: 'Relatos de compradores informados e preparados',
      ctaText1: 'Começar agora',
      ctaText2: 'Acessar Guia Estratégico',
    },
    images: {},
  },
  {
    id: 'authority',
    name: 'Autoridade',
    texts: {
      badge: 'Experiência Dual',
      title: 'Este conteúdo foi concebido por quem domina, as duas perspectivas da mesa de negociação — a do comprador e a do vendedor.',
      person1Badge: 'Especialista',
      person1Name: 'Francis Poloni',
      person1Desc: 'Atua desde 2018 no setor de integração fotovoltaica e consultoria onde assessorou tanto no lado do comprador (Buy-Side) quanto no lado do vendedor (Sell-Side), ajudando na tomada de decisões inteligentes e seguras.',
      person1Tag: 'Especialista Visão Buy-Side (Comprador)',
      person1Experience: '+7 Anos',
      person1ExperienceLabel: 'de experiência',
      person2Badge: 'Especialista',
      person2Name: 'Ovídio Collesi',
      person2Desc: 'Com vasta experiência em venda e pós venda no setor de energia solar fotovoltaica desde 2020, teve passagens por marketplaces, distribuidores, integração solar e certificadora, trazendo uma visão completa do lado do vendedor e do suporte técnico.',
      person2Tag: 'Especialista Visão Sell-Side (Vendedor)',
      person2Experience: '+5 Anos',
      person2ExperienceLabel: 'de experiência',
    },
    images: {
      francis: '/assets/Francis Poloni LP PRO.jpg.jpeg',
      ovidio: '/assets/Ovídio2.png',
    },
  },
  {
    id: 'lead-magnet',
    name: 'Lead Magnet',
    texts: {
      badge: 'Conteúdo Exclusivo',
      title: 'Ainda tem dúvidas sobre o impacto do Manual Buy-Side?',
      subtitle: 'Garanta agora seu e-book grátis e entenda por que a imersão Solar Buy-Side faz vendedores venderem mais e melhor.',
      feature1: 'Os 3 riscos na compra de sistemas solares',
      feature2: 'As 4 fases que seu cliente seguirá antes de comprar',
      feature3: 'Como sua proposta será avaliada e comparada',
      feature4: 'O índice detalhado do Manual Solar Buy-Side',
      ctaButton: 'Baixar E-book Gratuito',
      ctaSubtext: 'PDF Interativo • 24 páginas • Acesso imediato',
      modalTitle: 'Baixe seu E-book',
      modalSubtitle: 'Preencha seus dados para receber o E-book Manual Solar Buy-Side',
      successTitle: 'Perfeito!',
      successMessage: 'Confira seu e-mail para baixar o E-book Manual Solar Buy-Side',
    },
    images: {
      ebook: '/assets/Capa do Vendedor E-book  - OF.png',
    },
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    texts: {
      title: 'Fique por dentro das novidades',
      highlightWord: 'novidades',
      subtitle: 'Cadastre seu e-mail para receber lançamentos exclusivos, atualizações e conteúdos sobre o mercado solar.',
      placeholder: 'seu@email.com',
      ctaButton: 'Cadastrar',
      successButton: 'Cadastrado!',
      successMessage: 'E-mail cadastrado com sucesso! Fique atento às novidades.',
      privacyNote: '🔒 Seus dados estão seguros conosco. Não compartilhamos com terceiros.',
    },
    images: {},
  },
  {
    id: 'faq',
    name: 'FAQ',
    texts: {
      title: 'Ficou com dúvidas?',
      subtitle: 'Nossa equipe de especialistas está pronta para ajudar você a entender como o Manual Buy-Side pode transformar sua operação comercial.',
      ctaButton: 'Fale com a equipe Buy-Side',
      sectionTitle: 'Perguntas Frequentes',
      faq1Question: 'Como acessar meu produto?',
      faq1Answer: 'Você receberá o acesso ao Manual Solar Buy-Side por e-mail, por meio da plataforma online GREENN. Esta plataforma atua como intermediadora digital entre clientes e produtores, disponibilizando conteúdos, soluções e ferramentas tecnológicas.\n\nVocê receberá o Manual Solar Buy-Side e o bônus grátis Guia do Vendedor por e-mail em PDF, e ele virá personalizado com seu nome e CPF ou CNPJ.\n\nVocê poderá acessar o manual por meio de computador, celular, tablet ou outro dispositivo digital. No entanto, devido à formatação do manual, recomendamos enfaticamente o uso de um computador ou tablet para uma experiência de leitura e aproveitamento mais otimizada do material.',
      faq2Question: 'Como funciona o prazo de garantia e a solicitação de devolução?',
      faq2Answer: 'O reembolso de uma compra de um produto digital é um direito garantido pelo Código de Defesa do Consumidor (Lei nº 8.078, Artigo 49) e pode ser solicitado em até 7 dias a partir da data de assinatura ou do recebimento do produto.',
      faq3Question: 'Política de devolução: como proceder para o reembolso?',
      faq3Answer: 'Para formalizar o pedido de reembolso do valor despendido, o Comprador deverá remeter sua solicitação ao endereço eletrônico contato@buyside.com.br. A comunicação deverá conter, obrigatoriamente, o número de referência da transação e a exposição detalhada da(s) razão(ões) que fundamenta(m) o pleito de cancelamento.\n\nAs condições para efetivação do reembolso pautam-se nas Regras Gerais estabelecidas pela plataforma GREENN. Para informações adicionais e consulta integral às diretrizes aplicáveis, o Comprador poderá acessar o seguinte link: https://greenn.com.br/termos-de-compra-greenn/\n\nSolicitação de Cancelamento e Reembolsos na GREENN\n\nPrazo: O Comprador pode solicitar o reembolso dos valores pagos, os prazos mínimos estabelecidos pela legislação para garantia são entre 07 a 30 dias, mas dependem exclusivamente do prazo estabelecido pelo Produtor, que é o responsável direto por esta informação e pelas solicitações e as autorizações dos reembolsos. O prazo terá início a partir da efetivação da compra, pedidos de reembolso fora do prazo deverão ser feitos diretamente ao Produtor, e se por ele autorizados, salvo quando o reembolso deva ser processado para garantir os interesses do GREENN e para o cumprimento da lei.\n\nO GREENN pode recusar o reembolso integral dos valores pagos, ainda que dentro do prazo de garantia, na hipótese do Comprador ter usufruído de todo o Produto adquirido, como por exemplo, assistido a todas as aulas de um curso, participado de um evento, ou ter feito o download de todos os arquivos disponíveis, deixando o GREENN e o Produtor em clara desvantagem.\n\nForma de processamento: O reembolso será processado através do mesmo meio de pagamento escolhido pelo Comprador no momento da compra, por questões legais e processuais. O reembolso é realizado por meio de transferência bancária deve ocorrer em até 30 (trinta) dias, contados da data de solicitação. Nos casos de reembolso por meio de cartão de crédito, o GREENN fará a solicitação de estorno, mas a conclusão deste processo dependerá exclusivamente das operadoras de cartão, sem qualquer gerência do GREENN e poderá levar um prazo de 30 a 60 dias, após o pedido de estorno.\n\nSe o reembolso não ocorrer dentro dos prazos acima, o Comprador deverá entrar em contato com o GREENN. Se o reembolso for por intermédio de cartão de crédito, findado o prazo de 90 (noventa) dias, o Comprador se compromete a enviar as cópias de suas faturas para que o Greenn possa endereçar este assunto perante a operadora e finalizar o processo de reembolso. O comprador concorda que o não envio das faturas impede o Greenn de dar seguimento ao processo de investigação e conclusão do processo de estorno do pagamento.\n\nCanal de Reclamações: O Comprador pode solicitar cancelamento de sua compra de maneira independente, através do link www.reclamacao.greenn.com.br , bastando informar corretamente os dados solicitados e seguindo os procedimentos e orientações anteriormente colocados quanto a legalidade e prazos.',
    },
    images: {},
  },
  {
    id: 'privacy-policy',
    name: 'Política de Privacidade',
    texts: {
      content: 'Conteúdo da política de privacidade...',
    },
    images: {},
  },
  {
    id: 'terms-of-use',
    name: 'Termos de Uso',
    texts: {
      content: 'Conteúdo dos termos de uso...',
    },
    images: {},
  },
  {
    id: 'antipiracy',
    name: 'Medidas Antipiratarias',
    texts: {
      content: 'Conteúdo das medidas antipiratarias...',
    },
    images: {},
  },
]
